### PR TITLE
feature / Create mu.yaml

### PR DESCRIPTION
**Pull request by beaugrzanich**
adding Mauritius holidays to settings

### CODE REVIEW

**Review by ghiculescu — APPROVED** [review]

**Comment by mattkuras** [comment]
@ghiculescu Is this good for me to merge?

**Review by tyler-mcwilliam — APPROVED** [review]
cool

**Comment by tyler-mcwilliam** [comment]
It sounds like @beaugrzanich is still having trouble getting these to show in the holiday region list 
image

Might be missing a step somewhere in here:
https://tandadocs.atlassian.net/wiki/spaces/DEV/pages/391610372/How+to+add+public+holidays

**Comment by ghiculescu** [comment]
did https://github.com/TandaHQ/docs/blob/master/applications/tanda-core/how-to/updating-public-holidays-in-tanda.md#making-updates get done? there should have been a payaus PR

**Comment by beaugrzanich** [comment]
Still having trouble with this. Can I get help whenever someone has time?

**Comment by ghiculescu** [comment]
@leonp1991 or @tyler-mcwilliam can you help ^

**Comment by tyler-mcwilliam** [comment]
> @leonp1991 or @tyler-mcwilliam can you help ^

https://github.com/TandaHQ/holidays/pull/22

**Comment by tyler-mcwilliam** [comment]
@beaugrzanich 
image

**Comment by beaugrzanich** [comment]
Ilysm

**Pull request merged**
